from module.ocr.ocr import  OcrWhiteLetterOnComplexBackground
import re
import cv2
import numpy as np
class FortressOcr(OcrWhiteLetterOnComplexBackground):
    box_thresh=0.2
    def pre_process(self, image):
        image = cv2.resize(image, (2560, 1920), interpolation=cv2.INTER_CUBIC)
        hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        mask = cv2.inRange(hsv, np.array([20,100,100]), np.array([40,255,255]))
        image[mask > 0] = [255,255,255]
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
        image = clahe.apply(gray)
        image = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
        return OcrWhiteLetterOnComplexBackground.pre_process(self,image)
    def after_process(self, result):
        result=result.replace('商','汤')
        result=result.replace('阿','汤')
        result=result.replace('溺','汤')
        result=result.replace('锅','涡')
        result=result.replace('能','熊')
        result=result.replace('日','田')
        result=result.replace('防','汤')
        result=result.replace('尚','汤')
        result=result.replace('烟','雷')
        result=result.replace('福','雷')
        result=result.replace('鸿','雷')    
        result=result.replace('凤','风')
        result=result.replace('从','风')
        result=result.replace('安','要')
        result=result.replace('装','塞')
        result=result.replace('勇','雷')
        result=result.replace('杨','汤')
        result=result.replace('菜','草')
        result=result.replace('卓','草')
        result=result.replace('小','川')
        result=result.replace('山','川')
        result=result.replace('霸','霜')
        result=result.replace('阁','涡')
        result=result.replace('中','鸟')
        result=result.replace('乌','鸟')
        result=result.replace('马','鸟')
        result=result.replace('子','云')
        result=result.replace('泥','泷')
        result=result.replace('洗','泷')
        result=result.replace('炭','泷')
        result=result.replace('发','泷')
        result=result.replace('医','泷')
        result=result.replace('陇','泷')
        result = re.sub('^铁.*', '铁之要塞', result)  
        result = re.sub('^田.*', '田之要塞', result)  
        result = re.sub('^土.*', '土之要塞', result)  
        result = re.sub('^熊.*', '熊之要塞', result)  
        result = re.sub('^汤.*', '汤之要塞', result)  
        result = re.sub('^涡.*', '涡之要塞', result)  
        result = re.sub('^霜.*', '霜之要塞', result)  
        result = re.sub('^水.*', '水之要塞', result)  
        result = re.sub('^火.*', '火之要塞', result)  
        result = re.sub('^雨.*', '雨之要塞', result)  
        result = re.sub('^草.*', '草之要塞', result)  
        result = re.sub('^川.*', '川之要塞', result)  
        result = re.sub('^雷.*', '雷之要塞', result)  
        result = re.sub('^风.*', '风之要塞', result)  
        result = re.sub('^海.*', '海之要塞', result)  
        result = re.sub('^泷.*', '泷之要塞', result)  
        result = re.sub('^云.*', '云之要塞', result)  
        result = re.sub('^鸟.*', '鸟之要塞', result)  
        return super().after_process(result)
