# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Duel:
      - Scheduler
      - Duel
      - DuelStorage
    FengRao:
      - Scheduler
      - FengRao
    SquadRaid:
      - Scheduler
      - SquadRaid
    Organization:
      - Scheduler
      - Organization
    SurvivalTrail:
      - Scheduler
      - SurvivalTrail
    TiLi:
      - Scheduler
      - TiLi
      - TiLiStorage
    Mission:
      - Scheduler
    Recruit:
      - Scheduler
      - Recruit
    MiJing:
      - Scheduler
      - MiJing




#    DataUpdate:
#      - Scheduler
#      - ItemStorage

Rewards:
  menu: 'collapse'
  page: 'setting'
  tasks:
    ZhaoCai:
      - Scheduler
      - ZhaoCai
    Freebies:
      - Scheduler
      - Freebies
    DailyReward:
      - Scheduler
      - DailyReward
    LeaderBoard:
      - Scheduler
      - LeaderBoard
    MonthlySignIn:
      - Scheduler
      - MonthlySignIn
    InformationClub:
      - Scheduler
      - InformationClub
    YiLeLaMian:
      - Scheduler
      - YiLeLaMian
    BattleOrder:
      - Scheduler
      - BattleOrder
      - BattleOrderStorage








# ==================== Weekly ====================
Weekly:
  menu: 'collapse'
  page: 'setting'
  tasks:
    CultivationRoad:
      - Scheduler
      - CultivationRoad
    Akatsuki:
      - Scheduler
      - Akatsuki

# ==================== Activity ====================
Activity:
  menu: 'collapse'
  page: 'setting'
  tasks:
    DingCiKaoRou:
      - Scheduler



# ==================== Tool ====================



