# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler
      - AccountStorage

# ==================== Daily ====================

Daily:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Duel:
      - Scheduler
      - Duel
    FengRao:
      - Scheduler
      - FengRao
    SquadRaid:
      - Scheduler
      - SquadRaid
    Organization:
      - Scheduler
      - Organization
    SurvivalTrail:
      - Scheduler
      - SurvivalTrail
    TiLi:
      - Scheduler
      - TiLi
      - TiLiStorage
    Mission:
      - Scheduler
      - MissionStorage
    Recruit:
      - Scheduler
      - Recruit
    MiJing:
      - Scheduler
      - MiJingType
      - MiJingStorage
    JiFenSai:
      - Scheduler
      - JiFenSai
      - JiFenSaiStorage
    Freebies:
      - Scheduler
      - FriendGifts
      - DailyShare
      - MailReward
      - PrivilegeWeeklyPackage
      - ZhaoCai
      - FreebiesStorage
      - DailyReward
      - LeaderBoard
      - MonthlySignIn
      - InformationClub
      - YiLeLaMian
    StorePurchase:
      - Scheduler
      - PrivilegeStore
      - OrganizationStore

    BattleOrder:
      - Scheduler
      - BattleOrder
      - BattleOrderStorage
    DataUpdate:
      - Scheduler
      - ItemStorage
# ==================== Weekly ====================
Weekly:
  menu: 'collapse'
  page: 'setting'
  tasks:
    CultivationRoad:
      - Scheduler
      - CultivationRoad
    Akatsuki:
      - Scheduler
      - Akatsuki
    PanRen:
      - Scheduler
      - PanRen
    Fortress:
      - Scheduler
    BattleField:
      - Scheduler
      - BattleField







# ==================== Activity ====================
Activity:
  menu: 'collapse'
  page: 'setting'
  tasks:
    DingCiKaoRou:
      - Scheduler
    QiuRiJi:
      - Scheduler



# ==================== Tool ====================



