import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Alas'
    Scheduler_ServerUpdate = '05:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_GameClient = 'android'  # android
    Emulator_PackageName = 'auto'  # auto, CN-Official
    Emulator_GameLanguage = 'auto'  # auto, cn
    Emulator_ScreenshotMethod = 'auto'  # auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy, nemu_ipc, ldopengl
    Emulator_ControlMethod = 'MaaTouch'  # minitouch, MaaTouch, ADB, uiautomator2
    Emulator_AdbRestart = False

    # Group `EmulatorInfo`
    EmulatorInfo_Emulator = 'auto'  # auto, NoxPlayer, NoxPlayer64, BlueStacks4, BlueStacks5, BlueStacks4HyperV, BlueStacks5HyperV, LDPlayer3, LDPlayer4, LDPlayer9, MuMuPlayer, MuMuPlayerX, MuMuPlayer12, MEmuPlayer
    EmulatorInfo_name = None
    EmulatorInfo_path = None

    # Group `Error`
    Error_Restart = 'game'  # game, game_emulator
    Error_SaveError = True
    Error_ScreenshotLength = 1
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_ScreenshotInterval = 0.3
    Optimization_CombatScreenshotInterval = 1.0
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # stay_there, goto_main, close_game, close_emulator

    # Group `Organization`
    Organization_OrganizationPray = True

    # Group `SquadRaid`
    SquadRaid_SquadRaidBenefit = True
    SquadRaid_SquadQuadrupleReward = False
    SquadRaid_SquadRaidFight = 'SquadSupport'  # SquadSupport, SquadMatch
    SquadRaid_SquadRaidFinishedCount = {}
    SquadRaid_SecondPassword = None

    # Group `SurvivalTrail`
    SurvivalTrail_SurvivalTrialResetTimes = 0

    # Group `TiLi`
    TiLi_LevelRestrictions = 72
    TiLi_DungeonFirst = True

    # Group `DuelWeekly`
    DuelWeekly_DuelWeeklyStatus = True
    DuelWeekly_DuelDaily = {}
    DuelWeekly_CurrentVictoryCount = {}
    DuelWeekly_TargetVictoryNumber = 10

    # Group `DuelExtended`
    DuelExtended_DuelExtendedStatus = True
    DuelExtended_DuelExtendedType = 'NoRestrictedBattle'  # NoRestrictedBattle
    DuelExtended_ExtendedCurrentScore = {}

    # Group `JiFenSai`
    JiFenSai_JiFenSaiSkipFight = True
    JiFenSai_JiFenSaiFilter = 'PowerLowest'  # PowerLowest, ScoreHighest, PowerLowerThanSelfAndScoreHigher, PowerLowerThanSelfAndScoreLower

    # Group `MiJingType`
    MiJingType_LuoYan = True
    MiJingType_LieYan = True
    MiJingType_ShuiLao = True
    MiJingType_GangTi = True
    MiJingType_LeiTing = True

    # Group `MiJingCount`
    MiJingCount_MiJingFightCount = 5
    MiJingCount_MiJingTicket = {}

    # Group `Freebies`
    Freebies_FriendGiftsStart = True
    Freebies_FriendGiftsFinishCount = {}
    Freebies_DailyShareStart = True
    Freebies_DailyShareFinishCount = {}
    Freebies_MailRewardClaim = True
    Freebies_MailRewardFinishCount = {}
    Freebies_LeaderBoardclaim = True
    Freebies_LeaderBoardFinishCount = {}
    Freebies_InformationClubSignIn = True
    Freebies_InformationClubSignInCount = {}
    Freebies_YiLeLaMianClaim = True
    Freebies_YiLeLaMianFinishCount = {}
    Freebies_MonthlySignIn = True
    Freebies_MonthlySignInFinishCount = {}
    Freebies_ActivityReward = True

    # Group `ZhaoCai`
    ZhaoCai_ZhaoCaiFree = True
    ZhaoCai_ZhaoCaiFinishCount = {}

    # Group `PrivilegeWeeklyPackage`
    PrivilegeWeeklyPackage_PrivilegeWeeklyPackageClaim = True
    PrivilegeWeeklyPackage_PrivilegPackageFinishCount = {}

    # Group `Recruit`
    Recruit_SkipNormalRecruit = False

    # Group `BattleOrder`
    BattleOrder_LikeAndShare = True
    BattleOrder_SCharacterFragments = '秽土长门'  # 忍战艾, 秽土解斑, 永恒佐助, 忍战樱, 九喇嘛鸣人, 死门凯, 忍战带土, 秽土柱间, 秽土鼬, 仙人兜, 秽土斑, 白面具, 秽土扉间, 百豪纲手, 秽土水门, 秽土日斩, 秽土长门, 斑, 柱间, 四代目雷影, 扉间, 神秘面具男, 须佐能乎鼬, 天道佩恩, 水门, 大蛇丸, 自来也
    BattleOrder_ACharacterFragments = '青年水门'  # 桃式显现博人, 忍战宁次, 博人传长十郎, 青年长门, 青年艾, 博人传达鲁伊, 青年水门, 忍战奇拉比, 博人传黑土, 须佐佐助, 秽土迪达拉, 博人传木叶丸, 九尾鸣人, 半蛇斗篷兜, 忍战我爱罗, 晓大蛇丸, 百豪樱, 照美冥, 鹰小队佐助, 奇拉比, 仙人鸣人, 神威卡卡西, 止水, 小南, 迪达拉, 鼬, 凯
    BattleOrder_CCharacterFragments = '左近右近'  # 左近右近, 火花, 学员鸣人, 山城青叶, 鬼童丸, 青, 萨克镫, 托斯砧
    BattleOrder_SExperienceCard = '秽土长门'  # 忍战艾, 秽土解斑, 永恒佐助, 忍战樱, 九喇嘛鸣人, 死门凯, 忍战带土, 秽土柱间, 秽土鼬, 仙人兜, 秽土斑, 白面具, 秽土扉间, 百豪纲手, 秽土水门, 秽土日斩, 秽土长门, 斑, 柱间, 四代目雷影, 扉间, 神秘面具男, 须佐能乎鼬, 天道佩恩, 水门, 大蛇丸, 自来也
    BattleOrder_AExperienceCard = '青年水门'  # 桃式显现博人, 忍战宁次, 博人传长十郎, 青年长门, 青年艾, 博人传达鲁伊, 青年水门, 忍战奇拉比, 博人传黑土, 须佐佐助, 秽土迪达拉, 博人传木叶丸, 九尾鸣人, 半蛇斗篷兜, 忍战我爱罗, 晓大蛇丸, 百豪樱, 照美冥, 鹰小队佐助, 奇拉比, 仙人鸣人, 神威卡卡西, 止水, 小南, 迪达拉, 鼬, 凯

    # Group `PrivilegeStore`
    PrivilegeStore_PrivilegeStoreFinishCount = {}
    PrivilegeStore_DailyFreeCoins = True

    # Group `OrganizationStore`
    OrganizationStore_MeritExchange = True
    OrganizationStore_MeritExchangeFilter = 'preset'  # preset, custom
    OrganizationStore_CustomMeritExchangeFilter = 'GiftBox > Coins > ReincarnationStone > Jade'

    # Group `SurvivalStore`
    SurvivalStore_SurvivalStoreExchange = True
    SurvivalStore_SurvivalStoreExchangeFilter = 'preset'  # preset, custom
    SurvivalStore_CustomSurvivalStoreFilter = 'TsuchikuraFragment > ReincarnationStone'

    # Group `ScoreStore`
    ScoreStore_ScoreStoreExchange = True
    ScoreStore_ScoreStoreChestPurchaseTimes = 1  # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    ScoreStore_ScoreStoreExchangeFilter = 'preset'  # preset, custom
    ScoreStore_CustomScoreStoreFilter = 'AdvancedSummoningScrollFragment > ScoreStoreChest'

    # Group `CultivationRoad`
    CultivationRoad_ClearRedDot = True
    CultivationRoad_CultivationFinish = False

    # Group `PanRen`
    PanRen_SecondPassword = None
    PanRen_NoRewardJoinOrNot = False
    PanRen_PanRenFinishCount = {}

    # Group `BattleField`
    BattleField_Type = '天之战场'  # 天之战场, 地之战场
    BattleField_BattleFieldFinishCount = {}
    BattleField_BattleFieldTargetScore = 1600

    # Group `Fortress`
    Fortress_FortressSelect = '火之要塞'  # 火之要塞, 水之要塞, 雷之要塞, 风之要塞, 土之要塞, 铁之要塞, 田之要塞, 熊之要塞, 汤之要塞, 涡之要塞, 霜之要塞, 雨之要塞, 草之要塞, 川之要塞, 海之要塞, 泷之要塞, 云之要塞, 鸟之要塞
    Fortress_FortressTargetScore = 40

    # Group `ItemStorage`
    ItemStorage_TiLi = {}
    ItemStorage_Golds = {}
    ItemStorage_Coins = {}
    ItemStorage_Fame = {}

    # Group `TiLiStorage`
    TiLiStorage_Dungeon = {}

    # Group `BattleOrderStorage`
    BattleOrderStorage_BattleOrderRank = {}
    BattleOrderStorage_BattleOrderActivityPoints = {}
    BattleOrderStorage_BattleOrderTaskProgress = {}

    # Group `MiJingStorage`
    MiJingStorage_MiJingCount = {}

    # Group `MissionStorage`
    MissionStorage_MissionAccept = {}

    # Group `AccountStorage`
    AccountStorage_AccountName = {}

    # Group `ActivityProgressStorage`
    ActivityProgressStorage_ActivityProgressToday = {}
    ActivityProgressStorage_ActivityProgressTodayCount = {}
    ActivityProgressStorage_ActivityProgressWeekly = {}
    ActivityProgressStorage_ActivityProgressWeeklyCount = {}
