import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Alas'
    Scheduler_ServerUpdate = '05:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_GameClient = 'android'  # android
    Emulator_PackageName = 'auto'  # auto, CN-Official
    Emulator_GameLanguage = 'auto'  # auto, cn
    Emulator_ScreenshotMethod = 'auto'  # auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy, nemu_ipc, ldopengl
    Emulator_ControlMethod = 'MaaTouch'  # minitouch, MaaTouch
    Emulator_AdbRestart = False

    # Group `EmulatorInfo`
    EmulatorInfo_Emulator = 'auto'  # auto, NoxPlayer, NoxPlayer64, BlueStacks4, BlueStacks5, BlueStacks4HyperV, BlueStacks5HyperV, LDPlayer3, LDPlayer4, LDPlayer9, MuMuPlayer, MuMuPlayerX, MuMuPlayer12, MEmuPlayer
    EmulatorInfo_name = None
    EmulatorInfo_path = None

    # Group `Error`
    Error_Restart = 'game'  # game, game_emulator
    Error_SaveError = True
    Error_ScreenshotLength = 1
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_ScreenshotInterval = 0.3
    Optimization_CombatScreenshotInterval = 1.0
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # stay_there, goto_main, close_game, close_emulator

    # Group `Organization`
    Organization_OrganizationPray = True

    # Group `SquadRaid`
    SquadRaid_SquadRaidBenefit = True
    SquadRaid_SquadRaidFight = 'SquadHelp'  # SquadHelp

    # Group `SurvivalTrail`
    SurvivalTrail_SurvivalTrialResetTimes = 0

    # Group `TiLi`
    TiLi_TiLiRemain = 0
    TiLi_LevelRestrictions = 72
    TiLi_DungeonFirst = True

    # Group `Duel`
    Duel_DuelWeeklyStatus = True
    Duel_CurrentVictoryNumber = 0
    Duel_TargetVictoryNumber = 10

    # Group `ItemStorage`
    ItemStorage_Credit = {}
    ItemStorage_StallerJade = {}

    # Group `Freebies`
    Freebies_FriendGifts = True
    Freebies_DailyShare = True
    Freebies_MailReward = True

    # Group `ZhaoCai`
    ZhaoCai_ZhaoCaiFree = True

    # Group `DailyReward`
    DailyReward_Weekly = True

    # Group `Recruit`
    Recruit_SkipNormalRecruit = False

    # Group `BattleOrder`
    BattleOrder_LikeAndShare = True
    BattleOrder_CharacterFragments = '秽土长门'  # 秽土解斑, 永恒佐助, 忍战樱, 九喇嘛鸣人, 死门凯, 秽土柱间, 秽土鼬, 仙人兜, 秽土斑, 白面具, 秽土扉间, 百豪纲手, 秽土水门, 秽土日斩, 秽土长门, 斑, 柱间, 四代目雷影, 扉间, 神秘面具男, 须佐能乎鼬, 天道佩恩, 水门, 大蛇丸, 自来也

    # Group `CultivationRoad`
    CultivationRoad_ClearRedDot = True

    # Group `TiLiStorage`
    TiLiStorage_Dungeon = {}

    # Group `BattleOrderStorage`
    BattleOrderStorage_BattleOrderRank = {}

    # Group `DuelStorage`
    DuelStorage_DuelDaily = {}
