import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Alas'
    Scheduler_ServerUpdate = '05:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_GameClient = 'android'  # android
    Emulator_PackageName = 'auto'  # auto, CN-Official
    Emulator_GameLanguage = 'auto'  # auto, cn
    Emulator_ScreenshotMethod = 'auto'  # auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy, nemu_ipc, ldopengl
    Emulator_ControlMethod = 'MaaTouch'  # minitouch, MaaTouch
    Emulator_AdbRestart = False

    # Group `EmulatorInfo`
    EmulatorInfo_Emulator = 'auto'  # auto, NoxPlayer, NoxPlayer64, BlueStacks4, BlueStacks5, BlueStacks4HyperV, BlueStacks5HyperV, LDPlayer3, LDPlayer4, LDPlayer9, MuMuPlayer, MuMuPlayerX, MuMuPlayer12, MEmuPlayer
    EmulatorInfo_name = None
    EmulatorInfo_path = None

    # Group `Error`
    Error_Restart = 'game'  # game, game_emulator
    Error_SaveError = True
    Error_ScreenshotLength = 1
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_ScreenshotInterval = 0.3
    Optimization_CombatScreenshotInterval = 1.0
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # stay_there, goto_main, close_game, close_emulator

    # Group `Organization`
    Organization_OrganizationPray = True

    # Group `SquadRaid`
    SquadRaid_SquadRaidBenefit = True
    SquadRaid_SquadRaidFight = 'SquadHelp'  # SquadHelp

    # Group `SurvivalTrail`
    SurvivalTrail_SurvivalTrialResetTimes = 0

    # Group `TiLi`
    TiLi_LevelRestrictions = 72
    TiLi_DungeonFirst = True

    # Group `Duel`
    Duel_DuelWeeklyStatus = True
    Duel_DuelDaily = {}
    Duel_CurrentVictoryCount = {}
    Duel_TargetVictoryNumber = 10

    # Group `JiFenSai`
    JiFenSai_DailyRewardClaim = True

    # Group `MiJingType`
    MiJingType_LuoYan = True
    MiJingType_LieYan = True
    MiJingType_ShuiLao = True
    MiJingType_GangTi = True
    MiJingType_LeiTing = True

    # Group `FriendGifts`
    FriendGifts_FriendGiftsStart = True
    FriendGifts_FriendGiftsFinishCount = {}

    # Group `DailyShare`
    DailyShare_DailyShareStart = True
    DailyShare_DailyShareFinishCount = {}

    # Group `MailReward`
    MailReward_MailRewardClaim = True
    MailReward_MailRewardFinishCount = {}

    # Group `PrivilegeWeeklyPackage`
    PrivilegeWeeklyPackage_PrivilegeWeeklyPackageClaim = True
    PrivilegeWeeklyPackage_PrivilegPackageFinishCount = {}

    # Group `ZhaoCai`
    ZhaoCai_ZhaoCaiFree = True
    ZhaoCai_ZhaoCaiFinishCount = {}

    # Group `DailyReward`
    DailyReward_Daily = True

    # Group `LeaderBoard`
    LeaderBoard_LeaderBoardclaim = True
    LeaderBoard_LeaderBoardFinishCount = {}

    # Group `MonthlySignIn`
    MonthlySignIn_MonthlySignIn = True
    MonthlySignIn_MonthlySignInFinishCount = {}

    # Group `InformationClub`
    InformationClub_InformationClubSignIn = True
    InformationClub_InformationClubSignInCount = {}

    # Group `YiLeLaMian`
    YiLeLaMian_YiLeLaMianClaim = True
    YiLeLaMian_YiLeLaMianFinishCount = {}

    # Group `Recruit`
    Recruit_SkipNormalRecruit = False

    # Group `BattleOrder`
    BattleOrder_LikeAndShare = True
    BattleOrder_CharacterFragments = '秽土长门'  # 秽土解斑, 永恒佐助, 忍战樱, 九喇嘛鸣人, 死门凯, 秽土柱间, 秽土鼬, 仙人兜, 秽土斑, 白面具, 秽土扉间, 百豪纲手, 秽土水门, 秽土日斩, 秽土长门, 斑, 柱间, 四代目雷影, 扉间, 神秘面具男, 须佐能乎鼬, 天道佩恩, 水门, 大蛇丸, 自来也

    # Group `PrivilegeStore`
    PrivilegeStore_PrivilegeStoreFinishCount = {}
    PrivilegeStore_DailyFreeCoins = True

    # Group `OrganizationStore`
    OrganizationStore_MeritExchangeFilter = 'preset'  # preset, custom
    OrganizationStore_CustomMeritExchangeFilter = '组织饰品礼盒 > 铜币 > 轮回石 > 忍玉'

    # Group `CultivationRoad`
    CultivationRoad_ClearRedDot = True

    # Group `PanRen`
    PanRen_SecondPassword = None
    PanRen_NoRewardJoinOrNot = False
    PanRen_PanRenFinishCount = {}

    # Group `BattleField`
    BattleField_Type = '天之战场'  # 天之战场, 地之战场
    BattleField_BattleFieldFinishCount = {}

    # Group `ItemStorage`
    ItemStorage_TiLi = {}
    ItemStorage_Golds = {}
    ItemStorage_Coins = {}
    ItemStorage_Fame = {}

    # Group `TiLiStorage`
    TiLiStorage_Dungeon = {}

    # Group `BattleOrderStorage`
    BattleOrderStorage_BattleOrderRank = {}
    BattleOrderStorage_BattleOrderActivityPoints = {}
    BattleOrderStorage_BattleOrderTaskProgress = {}

    # Group `JiFenSaiStorage`
    JiFenSaiStorage_JiFenSaiDailyRewardClaim = {}

    # Group `MiJingStorage`
    MiJingStorage_MiJingCount = {}

    # Group `MissionStorage`
    MissionStorage_MissionAccept = {}

    # Group `AccountStorage`
    AccountStorage_AccountName = {}
